name: pgvector
icon: postgres
type: db
from: postgres
fromVersionConstraint: "^1.1.0"
fromVersion: "1.1.1"
title: PostgreSQL (pgvector)

options:
- version: '18'
  tag: '18-pgvector-1.46.0'

labels:
- pgvector
- postgres
- postgresql
